name: flutter_hrlweibo
description: flutter微博
platforms:
  android:
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  #https://github.com/flutter/plugins/tree/main/packages/shared_preferences/shared_preferences
  shared_preferences: ^2.0.15
  #https://github.com/rrousselGit/riverpod
  provider: ^6.0.3
  cupertino_icons: ^1.0.5
  #https://github.com/luanpotter/audioplayers
  audioplayers: ^1.0.1
  #https://github.com/flutterchina/dio
  dio: ^4.0.6
  #https://github.com/google/json_serializable.dart/tree/master/json_serializable
  json_annotation: ^4.4.0
  #https://github.com/best-flutter/flutter_swiper
  card_swiper : ^2.0.4
  #https://github.com/best-flutter/flutter_page_indicator
  flutter_page_indicator: ^0.0.3
  #https://github.com/flutter/plugins/tree/master/packages/video_player
  video_player: ^2.4.7
  # https://github:com/brianegan/chewie
  chewie: ^1.3.4
  #https://github.com/flutterchina/azlistview
  azlistview: ^2.0.0
  #https://github.com/flutterchina/lpinyin
  lpinyin: ^2.0.2
  # https://github:com/fluttercandies/extended_text_field:
  extended_text_field: ^10.1.1
  url_launcher: 5.3.0
  # https://github: com/fluttercandies/extended_nested_scroll_view:
  extended_nested_scroll_view: ^5.1.3
  #https://github.com/Daegalus/dart-uuid
  uuid: 3.0.1
  flutter_screenutil: ^0.5.2
  fluttertoast: ^8.0.9
  synchronized: ^2.1.0
  event_bus: ^2.0.0
  # https://github.com/theyakka/fluro
  fluro: ^2.0.3
  #https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: ^0.8.5
  #https://github.com/MisterJimson/flutter_keyboard_visibility
  flutter_keyboard_visibility: ^5.3.0
  #https://github.com/Baseflow/flutter-permission-handler
  permission_handler:   '^10.0.0'
  #https://pub.flutter-io.cn/packages/audio_recorder
  flutter_record_plugin:
    git:
      url: https://github.com/huangruiLearn/flutter_record_plugin.git
      ref: c8dfed9c235174b223b1ab9dcaeb894bfaadabad
dependency_overrides:
  platform: ^3.1.0
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#
#  # The "flutter_lints" package below contains a set of recommended lints to
#  # encourage good coding practices. The lint set provided by the package is
#  # activated in the `analysis_options.yaml` file located at the root of your
#  # package. See that file for information about deactivating specific lint
#  # rules and activating additional ones.
#  flutter_lints: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: HotSearch
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
